"""Type stubs for authy_cli."""

from typing import Optional

class AuthyError(Exception):
    """Base exception for all Authy errors."""
    code: str
    exit_code: int

class SecretNotFound(AuthyError): ...
class SecretAlreadyExists(AuthyError): ...
class AuthFailed(AuthyError): ...
class PolicyNotFound(AuthyError): ...
class AccessDenied(AuthyError): ...
class VaultNotInitialized(AuthyError): ...

class Authy:
    """Native Authy client backed by the Rust vault engine."""

    def __init__(
        self,
        *,
        passphrase: Optional[str] = None,
        keyfile: Optional[str] = None,
        from_env: bool = False,
    ) -> None: ...

    def get(self, name: str) -> str: ...
    def get_or_none(self, name: str) -> Optional[str]: ...
    def store(self, name: str, value: str, force: bool = False) -> None: ...
    def remove(self, name: str) -> bool: ...
    def rotate(self, name: str, new_value: str) -> int: ...
    def list(self, scope: Optional[str] = None) -> list[str]: ...
    def build_env_map(
        self,
        scope: str,
        uppercase: bool = True,
        replace_dash: Optional[str] = "_",
    ) -> dict[str, str]: ...
    def test_policy(self, scope: str, secret_name: str) -> bool: ...
    def init_vault(self) -> None: ...

    @staticmethod
    def is_initialized() -> bool: ...
