/* auto-generated by napi-rs — do not edit */
/* eslint-disable */

const { existsSync, readFileSync } = require('node:fs');
const { join } = require('node:path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

const localPath = join(__dirname, 'authy-cli.node');

// Try loading local .node file first (development builds)
if (existsSync(localPath)) {
  localFileExisted = true;
  try {
    nativeBinding = require(localPath);
  } catch (e) {
    loadError = e;
  }
}

if (!nativeBinding) {
  if (localFileExisted) {
    throw new Error(
      `Failed to load native binding.\n${loadError?.message ?? 'Unknown error'}`
    );
  }
  throw new Error(
    'Native binding not found. Run `npm run build` first.'
  );
}

module.exports = nativeBinding;
