/* auto-generated by napi-rs — do not edit */
/* eslint-disable */

const { existsSync } = require('node:fs');
const { join } = require('node:path');

const { platform, arch } = process;

let nativeBinding = null;
let loadError = null;

// Map platform + arch to napi-rs triple names
const triples = {
  'linux-x64': 'authy-cli.linux-x64-gnu.node',
  'linux-arm64': 'authy-cli.linux-arm64-gnu.node',
  'darwin-x64': 'authy-cli.darwin-x64.node',
  'darwin-arm64': 'authy-cli.darwin-arm64.node',
  'win32-x64': 'authy-cli.win32-x64-msvc.node',
};

// Try platform-specific file first, then local development build
const candidates = [
  triples[`${platform}-${arch}`],
  'authy-cli.node',
].filter(Boolean);

for (const name of candidates) {
  const filePath = join(__dirname, name);
  if (existsSync(filePath)) {
    try {
      nativeBinding = require(filePath);
      break;
    } catch (e) {
      loadError = e;
    }
  }
}

if (!nativeBinding) {
  const msg = loadError
    ? `Failed to load native binding: ${loadError.message}`
    : `No native binding found for ${platform}-${arch}. Run \`npm run build\` for local development.`;
  throw new Error(msg);
}

module.exports = nativeBinding;
